# Podfile
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '9.1'

use_frameworks!

# To decode json to models
# pod 'Argo'
# pod 'Curry'
pod 'Unbox'

pod 'GoogleMaps'

def testing_pods
    pod 'Quick', '~> 0.9.0'
    pod 'Nimble', '3.0.0'
end

target 'TransitAppTests' do
    testing_pods
end

target 'TransitAppUITests' do
    testing_pods
end