# Podfile

use_frameworks!

def testing_pods
    pod 'Quick', '~> 0.9.0'
    pod 'Nimble', '3.0.0'
end

target 'TransitAppTests' do
    testing_pods
end

target 'TransitAppUITests' do
    testing_pods
end